language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: PioJwaVgepHWu/GxfzXfZDbgHYalQbKccKQSgR0uDG7SCRNFyQzGvx88NA5HpOpwRfFGJnqjghBgY4WBzR2EPK3AW/PG+SeybccQtP8cLNoedgxKR9udHQ1DmZBBKp/mV5dOqdPtYtABCn3qH7aYHX2t/62lP1xalEfLlwhRu4hZRzAV+9Y74cCNSDGhLe9+B5TLS6OTwyG6RV6649kpNTvGKngs5d3VCp6naXVq3LlQQHYZG8fddHm3WgtScQThQVpjy08pRbJ38AMLgUEqFdobZo2zrwtBlEJ7vF677VgBtD/hnD1rj8dCTarbWOR1U8OdfxYO0Sk0Ai9EYedujiLbkfUaBJHUlljzOQfn5OThNjYrSyGjhSHbJrh8wDLYchBcWpuACJoSs4hsg8fbONqeza+L62aIS4+MR5kLyrp/tJ6i1RoML1QqRIhgwHqGG1HYANKXaqSo3755e5R2Y0+cNiF0SPI3maemiG+F2FvjBsgbsH2wumZSe3qUPD2wZgRQkUTcqWmlPIJgPJyxiDSanhg+9Lns6jrpHytrcO5vNQPe8EWevKTUoi62v4Fpv2pZsfAUyCH70P5HKeM5lZedxIlmyv4Eiu/3xBRUBO7SeUO82VvGBkhFwRfp45nfGzAudrLdpWObtpyhvmLElfqXDo8nsHpbXAolmpVr0d8=
  - secure: SWO/0OC6ZhsL4TTkZaTph6ASkLFLmMhI1PjEmMD5UYnaJE2Pn9ocfFVNceAjVdE8CuQv8VNTGpAvOgcoZSdFDdX3V+OrP4NDjfc3bU0TRvHzvVdKCJVHO6pqCAibi0qP6P+X3ATA8SLKy23qSczyrYIybEN9OKUx1nii8MdDA3igZ9OOii3Z95nFqjvu2LghAS0JJTY3FY5tsRAlixlp1X1OjKVFgQrLAp81QD8YG9054Vg9t9XPKp0r06xAtSXmGH411pwnjnR8IYBHxaLFAOyVZBig8zMMulc9yeKtCuu3qGxxov+jhJZl2i15cFSlhu1JVLLf+IKJvQsgSDcfrtCcdUiQYa8qCdda2PEZagmFj7KlJWoXJV8fz9XiIYxej+9mF3qSJK39irlGJuNbEysltkzIm0eVTr2GZIlbqk/eUa/Sx65evgAsxBLielGFjabhHm0ITmdVyZlP1NZ9mx2s058V1LU5g6ay5cn74b3SEA52aJ/O+MmN+7hoXRcNsymkwNup9bItvQvGluyhFckvmEcDfCtcoF7u9oXIcrHj9yMmW/n4EytixjX9vg1hSt0nXFYsZgpFmfFfn+NsqBeuHelzVYxedeQ7i1fN60NkYBu/Hv6v7FeIWaupBYGirOOdD6B3WIp5EPWeghk0Ry6CUgnzr2pjzbql/hfpIaM=
